"""Trusted comment read-back and re-read with the known host footer (#1043)."""

from __future__ import annotations

import json
from types import SimpleNamespace

import pytest

import coding_review_agent_loop.github as github_module
from coding_review_agent_loop.errors import AgentLoopError
from coding_review_agent_loop.github import (
    note_host_footer_observed,
    patch_verified_trusted_protocol_comment,
    patch_verified_trusted_protocol_comment_observed,
    post_verified_trusted_issue_protocol_comment,
    post_verified_trusted_pr_protocol_comment,
    post_verified_trusted_pr_protocol_comment_observed,
    read_authenticated_protocol_comments,
    reset_host_footer_log_latch,
)
from coding_review_agent_loop.protocol_markers import (
    KNOWN_HOST_COMMENT_FOOTER,
    TrustedBody,
    scan_reserved_markers,
    stored_body_matches_posted,
    strip_known_host_footer,
)

from coding_review_agent_loop.round_state import (
    PlanValidationDiagnosticPayload,
    encode_plan_validation_diagnostic_body,
)

from agent_loop_helpers import make_config


FOOTER = KNOWN_HOST_COMMENT_FOOTER
ACTOR = ("agent-loop", 7)
NEAR_MISSES = (
    # A different URL.
    "\n\n---\n_Generated by [Claude Code](http://claude.ai/code)_",
    # A missing blank line.
    "\n---\n_Generated by [Claude Code](https://claude.ai/code)_",
    # Extra trailing text or whitespace.
    FOOTER + "\n",
    FOOTER + " ",
    FOOTER + "\n\nsmuggled",
    # A doubled footer.
    FOOTER + FOOTER,
    # Ordinary prose.
    "\n\nThanks!",
)


def _body(text: str = "Visible label\n\n<!-- AGENT_MANAGED_CI_INTENT_V2 {} -->") -> TrustedBody:
    return TrustedBody.canonical(text, expected_tokens=("AGENT_MANAGED_CI_INTENT_V2",))


@pytest.fixture
def logged(monkeypatch):
    lines: list[str] = []
    monkeypatch.setattr(github_module, "log", lambda _config, message: lines.append(message))
    monkeypatch.setattr(github_module, "active_workdir", lambda config: None)
    reset_host_footer_log_latch()
    yield lines
    reset_host_footer_log_latch()


class _EchoRunner:
    """Echo each write the way a host that stores ``stored(posted)`` would."""

    def __init__(self, *, stored, envelope_extra=None, comment_id=41):
        self.stored = stored
        self.envelope_extra = dict(envelope_extra or {})
        self.comment_id = comment_id
        self.calls: list[list[str]] = []

    def run(self, args, *, cwd, check=True, input_text=None, **_kwargs):
        cmd = list(args)
        self.calls.append(cmd)
        posted = None
        for part in cmd:
            if isinstance(part, str) and part.startswith("body="):
                posted = part[len("body="):]
        if posted is None and input_text is not None:
            posted = json.loads(input_text)["body"]
        envelope = {
            "id": self.comment_id,
            "body": self.stored(posted),
            "user": {"login": ACTOR[0], "id": ACTOR[1]},
            "created_at": "2026-09-25T00:00:00Z",
        }
        envelope.update(self.envelope_extra)
        return SimpleNamespace(returncode=0, stdout=json.dumps(envelope), stderr="")


def _post_pr(tmp_path, runner, body=None):
    return post_verified_trusted_pr_protocol_comment_observed(
        runner,
        config=make_config(tmp_path),
        pr_number=7,
        body=body or _body(),
        expected_author_login=ACTOR[0],
        expected_author_id=ACTOR[1],
    )


def test_footer_constant_is_the_observed_suffix_and_carries_no_marker():
    assert FOOTER == "\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_"
    assert not FOOTER.endswith("\n")
    assert scan_reserved_markers(FOOTER) == ()
    assert "<!--" not in FOOTER


def test_strip_removes_exactly_one_trailing_footer_and_nothing_else():
    assert strip_known_host_footer("record" + FOOTER) == ("record", True)
    assert strip_known_host_footer("record") == ("record", False)
    # Never loops: a doubled footer keeps one footer attached.
    assert strip_known_host_footer("record" + FOOTER + FOOTER) == ("record" + FOOTER, True)
    # Never trims whitespace or touches earlier text.
    assert strip_known_host_footer("record" + FOOTER + "\n") == ("record" + FOOTER + "\n", False)
    assert strip_known_host_footer(FOOTER + "record") == (FOOTER + "record", False)


def test_stored_body_match_accepts_only_posted_or_posted_plus_one_footer():
    assert stored_body_matches_posted("posted", "posted") == (True, False)
    assert stored_body_matches_posted("posted" + FOOTER, "posted") == (True, True)
    for suffix in NEAR_MISSES:
        assert stored_body_matches_posted("posted" + suffix, "posted") == (False, False)
    assert stored_body_matches_posted(FOOTER + "posted", "posted") == (False, False)
    assert stored_body_matches_posted(None, "posted") == (False, False)


def test_readback_accepts_exact_footer_on_create_and_logs_once(tmp_path, logged):
    runner = _EchoRunner(
        stored=lambda posted: posted + FOOTER,
        envelope_extra={"updated_at": "2026-09-25T00:00:05Z"},
    )

    written = _post_pr(tmp_path, runner)
    again = _post_pr(tmp_path, runner)

    assert written.comment_id == 41 and again.comment_id == 41
    assert written.host_footer_observed is True
    assert written.server_updated_at == 1790294405
    assert len(logged) == 1 and "known comment footer" in logged[0]
    # The int-returning wrapper keeps its contract.
    assert post_verified_trusted_pr_protocol_comment(
        runner, config=make_config(tmp_path), pr_number=7, body=_body(),
        expected_author_login=ACTOR[0], expected_author_id=ACTOR[1],
    ) == 41


def test_readback_accepts_exact_footer_on_patch(tmp_path, logged):
    runner = _EchoRunner(stored=lambda posted: posted + FOOTER)

    written = patch_verified_trusted_protocol_comment_observed(
        runner, config=make_config(tmp_path), comment_id=41, body=_body(),
        expected_author_login=ACTOR[0], expected_author_id=ACTOR[1],
    )

    assert (written.comment_id, written.host_footer_observed) == (41, True)
    assert patch_verified_trusted_protocol_comment(
        runner, config=make_config(tmp_path), comment_id=41, body=_body(),
        expected_author_login=ACTOR[0], expected_author_id=ACTOR[1],
    ) == 41
    assert len(logged) == 1


@pytest.mark.parametrize(
    ("envelope_extra", "expected"),
    [
        ({"updated_at": "2026-09-25T00:10:00Z"}, 1790294400 + 600),
        ({}, None),
        # created_at is the comment's immutable creation time and is never a
        # stand-in for a PATCH's server time.
        ({"created_at": "2026-09-24T23:40:00Z"}, None),
        ({"updated_at": "not a time"}, None),
        ({"updated_at": 12}, None),
    ],
)
def test_server_updated_at_comes_only_from_updated_at(tmp_path, logged, envelope_extra, expected):
    runner = _EchoRunner(stored=lambda posted: posted, envelope_extra=envelope_extra)

    written = patch_verified_trusted_protocol_comment_observed(
        runner, config=make_config(tmp_path), comment_id=41, body=_body(),
        expected_author_login=ACTOR[0], expected_author_id=ACTOR[1],
    )

    assert written.server_updated_at == expected


@pytest.mark.parametrize("suffix", NEAR_MISSES)
def test_readback_rejects_near_miss_and_doubled_footers(tmp_path, logged, suffix):
    runner = _EchoRunner(stored=lambda posted: posted + suffix)

    with pytest.raises(AgentLoopError, match="returned a different body"):
        _post_pr(tmp_path, runner)
    with pytest.raises(AgentLoopError, match="returned a different body"):
        patch_verified_trusted_protocol_comment_observed(
            runner, config=make_config(tmp_path), comment_id=41, body=_body(),
            expected_author_login=ACTOR[0], expected_author_id=ACTOR[1],
        )
    assert logged == []


def test_readback_rejects_footer_inserted_before_the_record(tmp_path, logged):
    runner = _EchoRunner(stored=lambda posted: FOOTER.lstrip("\n") + "\n\n" + posted)

    with pytest.raises(AgentLoopError, match="returned a different body"):
        _post_pr(tmp_path, runner)


def test_local_host_without_footer_is_unchanged_and_silent(tmp_path, logged):
    runner = _EchoRunner(stored=lambda posted: posted)

    written = _post_pr(tmp_path, runner)

    assert (written.comment_id, written.host_footer_observed) == (41, False)
    assert logged == []


def _issue_body() -> TrustedBody:
    return encode_plan_validation_diagnostic_body(
        PlanValidationDiagnosticPayload(
            repository="OWNER/REPO",
            issue_number=1043,
            planning_generation=1,
            target_coder_round=1,
            prior_plan_subject=None,
            candidate_kind="plan_state",
            architecture_contract_version=1,
            execution_strategy_contract_version=1,
            risk_test_matrix_contract_version=1,
            expected_producer_login=ACTOR[0],
            expected_producer_id=ACTOR[1],
            failure_attempt=1,
            candidate_digest="1" * 64,
            category="deterministic",
            diagnostic="missing audit",
        )
    )


def test_issue_protocol_record_accepts_footer_and_returns_the_posted_body(tmp_path, logged):
    runner = _EchoRunner(stored=lambda posted: posted + FOOTER)
    body = _issue_body()

    posted = post_verified_trusted_issue_protocol_comment(
        runner, config=make_config(tmp_path), issue_number=1043, body=body,
        expected_author_login=ACTOR[0], expected_author_id=ACTOR[1],
    )

    assert posted.body == str(body)
    assert not posted.body.endswith(FOOTER)
    assert len(logged) == 1


@pytest.mark.parametrize("suffix", NEAR_MISSES)
def test_issue_protocol_record_rejects_near_miss_footers(tmp_path, logged, suffix):
    runner = _EchoRunner(stored=lambda posted: posted + suffix)

    with pytest.raises(AgentLoopError, match="returned a different body"):
        post_verified_trusted_issue_protocol_comment(
            runner, config=make_config(tmp_path), issue_number=1043, body=_issue_body(),
            expected_author_login=ACTOR[0], expected_author_id=ACTOR[1],
        )


class _PagedRunner:
    def __init__(self, comments):
        self.comments = comments

    def run(self, args, *, cwd, check=True, **_kwargs):
        endpoint = args[-1]
        if endpoint == "user":
            return SimpleNamespace(returncode=0, stdout=json.dumps({"login": ACTOR[0], "id": ACTOR[1]}))
        page = int(endpoint.rsplit("page=", 1)[1])
        return SimpleNamespace(returncode=0, stdout=json.dumps(self.comments if page == 1 else []))


def _rest(comment_id, body):
    return {
        "id": comment_id,
        "body": body,
        "user": {"login": ACTOR[0], "id": ACTOR[1]},
        "created_at": "2026-09-25T00:00:00Z",
        "updated_at": "2026-09-25T00:00:00Z",
    }


def test_authenticated_reread_strips_exactly_one_footer_at_ingestion(tmp_path, logged):
    view = read_authenticated_protocol_comments(
        _PagedRunner([
            _rest(1, "record"),
            _rest(2, "record" + FOOTER),
            _rest(3, "record" + FOOTER + FOOTER),
            _rest(4, "record" + FOOTER + "\n"),
        ]),
        config=make_config(tmp_path),
        surface_kind="pr",
        number=7,
    )

    bodies = {item.comment_id: item.body for item in view.authored}
    assert bodies[1] == "record"
    assert bodies[2] == "record"
    # One strip only: a doubled footer still reaches strict parsers with one
    # footer attached, and whitespace variants are untouched.
    assert bodies[3] == "record" + FOOTER
    assert bodies[4] == "record" + FOOTER + "\n"
    # Footers seen only on re-read are logged, once.
    assert len(logged) == 1 and "re-read" in logged[0]


def test_footer_log_latch_is_per_invocation(tmp_path, logged):
    config = make_config(tmp_path)

    note_host_footer_observed(config, "first")
    note_host_footer_observed(config, "second")
    assert len(logged) == 1
    reset_host_footer_log_latch()
    note_host_footer_observed(config, "third")
    assert len(logged) == 2
